import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
const logo = "/logo.png";
// Convert image to Base64
const getBase64Image = (url) => {
    return new Promise((resolve) => {
        const img = new Image();
        img.src = url;
        img.onload = () => {
            const canvas = document.createElement("canvas");
            canvas.width = img.width;
            canvas.height = img.height;

            const ctx = canvas.getContext("2d");
            ctx.drawImage(img, 0, 0);

            resolve(canvas.toDataURL("image/png"));
        };
    });
};

export const generateCategoryPDF = async (products, category) => {
    const doc = new jsPDF();
    const pageMargen = 20;
    const topMargin = 20;
    // Load logo
    const logoBase64 = await getBase64Image(logo);

    // Logo (top-left)
    doc.addImage(logoBase64, "PNG", pageMargen, topMargin, 20, 20);

    // Header
    doc.setFontSize(22);
    doc.setTextColor(34, 139, 34);
    doc.text("Narkh Nama", 105, topMargin + 10, { align: "center" });

    doc.setFontSize(16);
    doc.setTextColor(0);
    doc.text("Official Price List", 105, topMargin + 20, { align: "center" });

    // Category
    doc.setFontSize(12);
    doc.text(`Category: ${category}`, pageMargen, topMargin + 35);

    // Date
    const today = new Date().toLocaleDateString();
    doc.text(`Date: ${today}`, pageMargen, topMargin + 43);

    // Table
    autoTable(doc, {
        startY: topMargin + 50,
        margin: {
            left: pageMargen,
            right: pageMargen,
            top: 20,
            bottom: 20,
        },
        head: [["Product", "Urdu", "Price", "Unit"]],
        body: products.map((product) => [
            product.name,
            product.urdu,
            `Rs ${product.price}`,
            product.unit,
        ]),
        headStyles: {
            fillColor: [34, 139, 34],
        },
    });

    // Footer
    const finalY = doc.lastAutoTable.finalY + 15;

    doc.setFontSize(10);
    doc.text(
        "Government prices are subject to daily updates.",
        pageMargen,
        finalY
    );

    doc.text(
        "Generated by Narkh Nama",
        pageMargen,
        finalY + 8
    );

    // Save
    doc.save(
        `NarkhNama_${category}_${today.replaceAll("/", "-")}.pdf`
    );
};